//INICIAR SESION
export const LOGIN_EXITO = 'LOGIN_EXITO';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CERRAR_SESION = 'CERRAR_SESION';
export const SELECT_INSTITUCION = 'SELECT_INSTITUCION';
export const SELECT_ROL = 'SELECT_ROL';

//OBTENER USUARIO AUTENTICADO
export const USUARIO_AUTH_EXITO = 'USUARIO_AUTH_EXITO';
export const USUARIO_AUTH_ERROR = 'USUARIO_AUTH_ERROR';


//MATERIAS
export const LISTAR_MATERIAS_EXITO = 'LISTAR_MATERIAS_EXITO';
export const LISTAR_MATERIAS_ERROR = 'LISTAR_MATERIAS_ERROR';
export const SELECCIONA_MATERIA = 'SELECCIONA_MATERIA';

//UNIDADES NA = NIVEL ACADEMICO
export const LISTAR_UNIDADES_MATERIA_NA_EXITO = 'LISTAR_UNIDADES_MATERIA_NA_EXITO';
export const LISTAR_UNIDADES_MATERIA_NA_ERROR = 'LISTAR_UNIDADES_MATERIA_NA_ERROR';

//NA = NIVELES ACADEMICOS
export const LISTAR_NA_EXITO = 'LISTAR_NA_EXITO';
export const LISTAR_NA_ERROR = 'LISTAR_NA_ERROR';
export const SELECCIONA_FILTRO_NA = 'SELECCIONA_FILTRO_NA';
